services:
  postgres:
    image: postgres:16.9-bullseye
    env_file:
      - database/.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  flyway:
    image: flyway/flyway:11
    env_file:
      - database/.env
    command: migrate -target=${MIGRATION_VERSION}
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_NAME}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      #- FLYWAY_BASELINE_ON_MIGRATE=false (future update)
      - MIGRATION_VERSION=${MIGRATION_VERSION:-}
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge